### ISSUE TITLE
export PATH=/Applications/CMake.app/Contents/bin:$PATH

### ISSUE THREAD

**Issue by PeiChenWu** [BitTiger-MP/DS502-AI-Engineer#1]
這個指令有需要做更改嗎？
$path部分

本身是機械工程師...對指令不是很了解..

**Comment by xiw54** [comment]
cmake已经装了是吗？在application里面，不用改

**Comment by PeiChenWu** [comment]
我沒有在application裡面 看到cmake..
cmake 安裝了

**Comment by xiw54** [comment]
你application folder里面没有cmake？在整个mac文件夹里面搜一下，如果安装了应该在application里，如果我没有记错我是drag n drop进application folder的
