### ISSUE TITLE
无法import Caffe

### ISSUE THREAD

**Issue by iamxhc** [BitTiger-MP/DS502-AI-Engineer#15]
Caffe以及Anaconda都安装好了，Make Runtest也完成了，不过在Terminal里似乎无法import Caffe。不知道是不是我的命令打错了，还是没有安装正确 -- 错误显示“no module named caffe”
<img width="572" alt="screen shot 2017-07-08 at 5 26 04 pm" src="https://user-images.githubusercontent.com/29770049/27990171-078b6ddc-6403-11e7-8a0d-c2009fc0e114.png">

**Comment by ZezhouLi** [comment]
**这个其实是caffe没加到Python路径上的问题**

- mkdir ~/python
- cd caffe
- mv /python/caffe ~/python

**最后一步把caffe加入Pythonpath，我们直接写入bash_profile里**

- open ~/.bash_profile
- export PYTHONPATH=~/python:$PYTHONPATH

**重启mac**

**Comment by iamxhc** [comment]
<img width="571" alt="screen shot 2017-07-15 at 4 25 56 pm" src="https://user-images.githubusercontent.com/29770049/28243336-64bb5cf2-697a-11e7-9115-a992309e94a9.png">
以及按要求做了，但是还是无法import Caffe，错误提示也一模一样。
