### ISSUE TITLE
MXNET Week2 Homework(Deadline: July 25) -- submit

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#20]
Please submit the link of your homework here.

**Comment by shf0328** [comment]
[HF Shi mxnet hw2](https://github.com/shf0328/MXNET_course/blob/master/mxnet-week2/train_compare.ipynb)

**Comment by ChuckTan123** [comment]
@shf0328 
Really Good job! I am so happy you wrote the report in python notebook. 
I have serval comments:

1) I can't see the pdf file in the link you gave. To visualize the plot directly in ipython notebook, you can do "mx.viz.plot_network(cnn_model, title="cnn", save_format="pdf", hide_weights=True)" rather than "plot = mx.viz.plot_network(cnn_model, title="cnn", save_format="pdf", hide_weights=True)
plot.render("CNN")"

2) If possible(still optional), please try to implement google inception module to see any improvement.

**Comment by jianglong98** [comment]
i found issue when i am running LN [1]. I got alarm with "no module named data" , any idea?

**Comment by shf0328** [comment]
@ChuckTan123 I update the link for pdf. As for the inception model, I'll try to finish it if I get time.

**Comment by dhzhd1** [comment]
Resubmit:
https://github.com/dhzhd1/MXNET_course/tree/master/mxnet-week2 

[Move the submition from https://github.com/ChuckTan123/MXNET_course/issues/1 to here]

**Comment by jianglong98** [comment]
https://github.com/jianglong98/ai/blob/master/homework/Chuck/MXNET/mxnet-week2/train_cnn.py

Train_mlp result
INFO:root:Epoch[9] Train-accuracy=0.993333
INFO:root:Epoch[9] Time cost=1.936
INFO:root:Epoch[9] Validation-accuracy=0.975700

Train CNN result
INFO:root:Epoch[4] Train-accuracy=0.998889
INFO:root:Epoch[4] Time cost=148.600
INFO:root:Epoch[4] Validation-accuracy=0.992300

**Comment by ChuckTan123** [comment]
@jianglong98 
Great job. CNN is 100 time slower than MLP  with higher accuracy as our expected. 
I already update the issue about the graphviz package. Please check that out, and submit the plot file. Contact me if further issues. 

You can also try to implement inception module, or try to use gpu instance. But they are bonus questions :)

**Comment by jianglong98** [comment]
Added CNN and MLP plot PDF files. The graphviz packet has been installed successfully, now it works properly

**Comment by xintongxia** [comment]
[MLP + CNN](https://github.com/xintongxia/DS502/blob/master/Chuck_course/mxnet-week2/mlp_sym.py)

[network graph](https://github.com/xintongxia/DS502/blob/master/Chuck_course/mxnet-week2/network.gv.pdf)

[Result](https://github.com/xintongxia/DS502/blob/master/Chuck_course/mxnet-week2/result.txt)

**Comment by xiw54** [comment]
Resubmit from old issue (for tracking purpose only, no change has been made yet. Will take suggestions from Chuck, thank you~~):

https://github.com/xiw54/DS502_Homework/tree/master/week3_codelab_mxnet
Xin (Output saved in Readme.md and network visualization saved in mlp.gv.pdf.

**Comment by xxu46** [comment]
[Ruochen Xu](https://github.com/xxu46/DS502-chunk)

**Comment by yangjiqi** [comment]
[Code for CNN & MLP ](https://github.com/yangjiqi/DS502/tree/master/hw%20for%20codelabs/week2/mxnet-cnn)
[Structure Visualization for CNN](https://github.com/yangjiqi/DS502/blob/master/hw%20for%20codelabs/week2/mxnet-cnn/cnn.pdf)

### Sample Running Results:
- Train-accuracy=1.000000
- Time cost=86.580
- Validation-accuracy=0.992600

**Comment by FanW123** [comment]
[CNN code](https://github.com/FanW123/DS502/blob/master/MXNET/mxnet-week2/mlp_sym.py/ "CNN code")
[CNN structure visualization](https://github.com/FanW123/DS502/blob/master/MXNET/mxnet-week2/CNN.pdf/ "CNN structure visualization")

Comparison | MLP | My CNN
---- | --- | ---
Acc(5 epoch) | 0.9731| 0.9982
CPU Epoch time | 2.152 | 519

**Comment by jinscript** [comment]
[Jin's MXNet homework ](https://github.com/jinscript/DS502/tree/master/Chuck_Homework/homework2)

**Comment by kevinHbsong0517** [comment]
[Hongbo Song's homework](https://github.com/kevinHbsong0517/MXNET_course/tree/master/mxnet-week2)


Comparison | MLP | Hongbo CNN
-- | -- | --
Acc(5 epoch Train ACC) | 0.986162 | 0.996667
Acc(5 epoch CV) | 0.975300 | 0.993300
CPU 5 Epoch time | 1.461 |197.951
GPU 5 Epoch time | 1.67 | 41.557

**Comment by BryanBo-Cao** [comment]
[Bryan's Homework](https://github.com/BryanBo-Cao/X-lab)
1. [mxnet-week2/mlp_sym.py](https://github.com/BryanBo-Cao/X-lab/blob/master/mxnet-practice/mxnet-week2/mlp_sym.py)
[mxnet-week2/train_mlp.py](https://github.com/BryanBo-Cao/X-lab/blob/master/mxnet-practice/mxnet-week2/train_mlp.py)
2. [Bryan_MLP](https://github.com/BryanBo-Cao/X-lab/blob/master/mxnet-practice/mxnet-week2/Bryan_MLP.pdf)
[Bryan_CNN](https://github.com/BryanBo-Cao/X-lab/blob/master/mxnet-practice/mxnet-week2/Bryan_CNN.pdf)
3. [MLP vs CNN](https://github.com/BryanBo-Cao/X-lab/blob/master/mxnet-practice/mxnet-week2/comparison_MLP_CNN.md)

**Comment by cyMMyc** [comment]
Cynthia's [homework](https://github.com/cyMMyc/AI-Engineer/tree/master/chuck-mxnet-h2)
Epoch[5] Train-accuracy=0.991717
Epoch[5] Time cost=260.331
Epoch[5] Validation-accuracy=0.994200

**Comment by zzx498636727** [comment]
[Zexuan's HW2](https://github.com/zzx498636727/DS502-AI-Engineer/tree/master/DS502-1702/MXNET_course/mxnet-week2):

|Comparison | MLP | CNN|

|Acc(5 epoch) |0.987071|0.997576|

|CPU Epoch time |1.469|57.159|

**Comment by xiemd** [comment]
[mlp_sym.py](https://github.com/xiemd/D502_homework/blob/master/codelab-week2_mxnet/mlp_sym.py)
[CNN.pdf](https://github.com/xiemd/D502_homework/blob/master/codelab-week2_mxnet/CNN.pdf)
[MLP.pdf](https://github.com/xiemd/D502_homework/blob/master/codelab-week2_mxnet/MLP.pdf)
**CNN**
Train-accuracy=0.996364
Time cost=209.648

**Comment by herohunfer** [comment]
[Yan Wang mxnet week2 homework](https://github.com/herohunfer/homework/blob/master/mxnet-week2-Chuck)

**Comment by ChuckTan123** [comment]
@xxu46 Good job. What is "CV"?

**Comment by ChuckTan123** [comment]
@yangjiqi Good to see you both posted training and testing accuracy.

**Comment by ChuckTan123** [comment]
@FanW123 Good job, you can also try to do some research about # of parameters vs accuracy separately in MLP and CNN to see the parameters efficiency for each network architecture.

**Comment by ChuckTan123** [comment]
@jinscript  can you also post the accuracy vs speed table?

**Comment by ChuckTan123** [comment]
@kevinHbsong0517  Nice job. You can easily change the data path to cifar10.

**Comment by ChuckTan123** [comment]
@BryanBo-Cao Nice job. Your network is much deeper than others. It needs more training epochs. You can try shallow CNN first. And also try BN right after data.

**Comment by ChuckTan123** [comment]
@cyMMyc try 3*3 to see any difference in acc and speed

**Comment by ChuckTan123** [comment]
@zzx498636727 The difference between MLP and CNN will be more significant in the more complicated task.

**Comment by ChuckTan123** [comment]
@xiemd is time cost epoch time or total training time?

**Comment by ChuckTan123** [comment]
@herohunfer Good Job. Can you also post training results here?
