### ISSUE TITLE
Cannot print pdf file issue- related to PATH

### ISSUE THREAD

**Issue by jianglong98** [BitTiger-MP/DS502-AI-Engineer#26]
**Log file below for reference, I have checked PATH but looks ok**
Captured related code in train_mlp.py
 # Viz the graph and save the plot for debugging
    **plot = mx.viz.plot_network(model, title="mlp", save_format="pdf", hide_weights=True)
    plot.render("MLP")**

(/Users/jianglong/anaconda) Jiangs-MacBook-Pro:mxnet-week2 jianglong$ ls
MLP                             data.pyc                        mxnet_mlp_cnn_jiang.ipynb       t10k-labels-idx1-ubyte.gz       train-labels-idx1-ubyte.gz
README.md                       mlp_sym.py                      mxnet_mlp_cnn_jiang.py          test.jpg                        train_mlp.py
data.py                         mlp_sym.pyc                     t10k-images-idx3-ubyte.gz       train-images-idx3-ubyte.gz
(/Users/jianglong/anaconda) Jiangs-MacBook-Pro:mxnet-week2 jianglong$ python mlp_sym.py
(/Users/jianglong/anaconda) Jiangs-MacBook-Pro:mxnet-week2 jianglong$ python train_mlp.py
INFO:root:train-labels-idx1-ubyte.gz exists, skip to downloada
INFO:root:train-images-idx3-ubyte.gz exists, skip to downloada
INFO:root:t10k-labels-idx1-ubyte.gz exists, skip to downloada
INFO:root:t10k-images-idx3-ubyte.gz exists, skip to downloada
Traceback (most recent call last):
  File "train_mlp.py", line 21, in <module>
    plot.render("MLP")
  File "/Users/jianglong/anaconda/lib/python2.7/site-packages/graphviz/files.py", line 171, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/Users/jianglong/anaconda/lib/python2.7/site-packages/graphviz/backend.py", line 127, in render
    raise ExecutableNotFound(args)
**graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'MLP'], make sure the Graphviz executables are on your systems' PATH**

(/Users/jianglong/anaconda) Jiangs-MacBook-Pro:mxnet-week2 jianglong$ env | grep site-packages
**PATH=/Users/jianglong/anaconda/bin:/Users/jianglong/anaconda/lib/python2.7/site-packages**:/Users/jianglong/anaconda/bin:/Users/jianglong/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/jianglong/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/jianglong/Library/Android/sdk/platform-tools:/Users/jianglong/Library/Android/sdk/tools:/Users/jianglong/Library/Android/sdk/platform-tools:/Users/jianglong/Library/Android/sdk/tools
CONDA_PATH_BACKUP=/Users/jianglong/anaconda/lib/python2.7/site-packages:/Users/jianglong/anaconda/bin:/Users/jianglong/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/jianglong/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/jianglong/Library/Android/sdk/platform-tools:/Users/jianglong/Library/Android/sdk/tools:/Users/jianglong/Library/Android/sdk/platform-tools:/Users/jianglong/Library/Android/sdk/tools

**Comment by ChuckTan123** [comment]
@jianglong98 
for mac, try "brew install graphviz", then run "pip install graphviz"

for ubuntu, try "sudo apt-get install graphviz", then run "pip install graphviz"

Tell me if any further issues

**Comment by jianglong98** [comment]
Installed and print PDF now, issue can be closed
