### ISSUE TITLE
make runtest make pytest error很多

### ISSUE THREAD

**Issue by PeiChenWu** [BitTiger-MP/DS502-AI-Engineer#3]
make runtest
make pytest

跑這兩格指令 出現很多error...

**Comment by xiw54** [comment]
最好是把error贴出来，有一些常见的在make runtest出错你可以参考这个帖子http://blog.csdn.net/xhhxllpp/article/details/73369062，make sure you have all dependencies/libs installed, especially like numpy and scikit-image....
