### ISSUE TITLE
MXNET Week3 Homework(Deadline: Aug 8) -- submit

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#30]
Submit the link of .ipynb file WITH plotted output.

**Comment by shf0328** [comment]
[HF's MXNET homework](https://github.com/shf0328/MXNET_course/blob/master/mxnet-week3/HW3/Homework3.ipynb)

**Comment by dhzhd1** [comment]
[John Li MXNET Homework3](https://github.com/dhzhd1/MXNET_course/blob/master/mxnet-week3/HW3/Homework3.ipynb)

**Comment by herohunfer** [comment]
[YAN WANG mxnet week3 homework](https://github.com/herohunfer/homework/blob/master/mxnet-week3-Chuck/HW3/Homework3.ipynb)

**Comment by jinscript** [comment]
[Jin mxnet homework3](https://github.com/jinscript/DS502/blob/master/Chuck_Homework/homework3/homework3.ipynb)

**Comment by xiw54** [comment]
https://github.com/xiw54/DS502_Homework/tree/master/HW3
Xin

**Comment by cyMMyc** [comment]
Cynthia [homework3](https://github.com/cyMMyc/AI-Engineer/blob/master/chuck-mxnet-h3/Homework3.ipynb)

**Comment by kevinHbsong0517** [comment]
[Hongbo Song HW3](https://github.com/kevinHbsong0517/MXNET_course/blob/master/Homework3.ipynbl)

**Comment by BryanBo-Cao** [comment]
BryanBo-Cao 
[https://github.com/BryanBo-Cao/x/tree/master/mxnet-practice/mxnet-week3](https://github.com/BryanBo-Cao/x/tree/master/mxnet-practice/mxnet-week3)
[Homework3.ipynb](https://github.com/BryanBo-Cao/x/blob/master/mxnet-practice/mxnet-week3/Homework3.ipynb)

**Comment by xiemd** [comment]
[https://github.com/xiemd/D502_homework/tree/master/hw3](Mindong hw3)

**Comment by xiemd** [comment]
[Mindong HW3](https://github.com/xiemd/D502_homework/tree/master/hw3)

**Comment by lihaifand** [comment]
[Charlie's HW3](https://github.com/lihaifand/PythonPractice/tree/master/MXNET)

**Comment by guan4015** [comment]
[XIao's HW3](https://github.com/guan4015/DS502_AI_bittiger/blob/master/Chuck/mxnet-week3/Homework3.ipynb)

**Comment by RichardTMR** [comment]
[Homework from richard](https://github.com/RichardTMR/homework/blob/master/week3/mxnet-part/HW3/Homework3.ipynb)

**Comment by yangjiqi** [comment]
[Jiqi's MXNet Homework3](https://github.com/yangjiqi/DS502/tree/master/hw%20for%20codelabs/MXNet/HW3)

**Comment by FanW123** [comment]
[MXNET Homework3 by Fan Wang](https://github.com/FanW123/MXNET-project/tree/master/mxnet-week3)

**Comment by jianglong98** [comment]
Jiang Long MXNET mxnet hw3 [https://github.com/jianglong98/ai/blob/master/homework/Chuck/MXNET/mxnet-week3/HW3/Homework3.ipynb](url)
