### ISSUE TITLE
Capstone: Object Detection [Deadline Spet 20th]

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#36]

**Comment by dhzhd1** [comment]
Capstone Project Repository: 
[Road Object Detector](https://github.com/dhzhd1/road_obj_detect) 
[README.md](https://github.com/dhzhd1/road_obj_detect/blob/master/README.md)
[Result JSON File](https://github.com/dhzhd1/road_obj_detect/blob/master/rfcn/results.json)
[Demo Video](https://youtu.be/E1yphaZ0vAg)

**Comment by jinscript** [comment]
[Repo](https://github.com/jinscript/object-detection)
[Result IDL File](https://github.com/jinscript/object-detection/blob/master/test-2017-9-11.idl)
[Demo Video](https://drive.google.com/open?id=0B9ZLExv7U60PRVlXQ1NfbTl2RlU)

**Comment by kevinHbsong0517** [comment]
[Hongbo's Repo](https://github.com/kevinHbsong0517/object_detection)

**Comment by lihaifand** [comment]
[Charlie's Repo](https://github.com/lihaifand/PythonPractice/tree/master/objectDetection)

**Comment by herohunfer** [comment]
[Yan's Repo](https://github.com/herohunfer/self_driving_car)
[Slides](https://docs.google.com/presentation/d/1W931zcnQkvN7FPAQVX86bKx41sU9b1oJ5NO2Zo6wAAU/edit)
[Demo Video]() (Pending)

Thanks Everyone!
