### ISSUE TITLE
DS502-1703-MXNET-Week1-Homework-Deadline(OCT 12)

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#38]
Please submit the link to your repository here for homework. 
I will review it and leave comments here. '
Please complete week1 part 1 homework, week1 part is not required for this week :)

**Comment by tomcattigerkkk** [comment]
[https://github.com/tomcattigerkkk/DS502-AI-Engineer/tree/master/DS502-1703/Homework/week1](url)

**Comment by florasdream** [comment]
https://github.com/florasdream/ds502hw1.git

**Comment by zyxstudycs** [comment]
https://github.com/zyxstudycs/DS502-week1-part1.
Yixing Zheng

**Comment by amigao0502** [comment]
https://github.com/amigao0502/AI.git

**Comment by zhengyjo** [comment]
https://github.com/zhengyjo/DS502-AI-Engineer/tree/master/DS502-1703

**Comment by selinatang95** [comment]
https://github.com/selinatang95/DS502/tree/master/MXNET_course

**Comment by CharlesLiuyx** [comment]
https://github.com/CharlesLiuyx/CharlesLiuyx.github.io

**Comment by xyzhang89** [comment]
[Xueying Zhang](https://github.com/xyzhang89/DeepLearning_MXNet_Exploration)

**Comment by bxguan8888** [comment]
[Boxuan Guan](https://github.com/bxguan8888/DS502-AI-Engineer)
