### ISSUE TITLE
DS502-1703-MXNET-Week1-part2-Homework-Deadline(OCT 18)

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#40]
Please finish wee1-part2 according to https://github.com/BitTiger-MP/DS502-AI-Engineer/blob/master/DS502-1703/MXNET_course/README.md

**Comment by tomcattigerkkk** [comment]
[Wei Luo](https://github.com/tomcattigerkkk/DS502-AI-Engineer/tree/master/DS502-1703/Homework/week1)

**Comment by ChuckTan123** [comment]
Great. But it seems like the CNN.pdf doesnt imply correct figure. Did you try to train the network with the architecture you built? What is the accuracy or performance under the diffierent environment (cpu vs gpu)?

**Comment by CharlesLiuyx** [comment]
[My homework source code](https://github.com/CharlesLiuyx/DS502-HW/tree/master/Week1-part2) 

Test complete!

**Comment by amigao0502** [comment]
[Homework2](https://github.com/amigao0502/AI/tree/master/mxnet-week1-part2)
When I tried to train my model, it some error. I will continue working on it

**Comment by tomcattigerkkk** [comment]
@ChuckTan123 Thanks for your advices. I have add some comparisons for MLP, CNN and CNN with Inception layer in README.md. 
CNN structure I have changed. It seems that I have named the pooling layer in my cnn function with a special name, then the next CNN layer uses the same pooling layer.
