### ISSUE TITLE
Capstone Object Detection Track Submit 

### ISSUE THREAD

**Issue by ChuckTan123** [BitTiger-MP/DS502-AI-Engineer#43]
Submit the link of your repo. Prediction results and Slides here.

**Comment by bxguan8888** [comment]
[boxuan guan](https://github.com/bxguan8888/ObjectDetection) 
includes code, model files, video(prediction result) and slides

**Comment by tomcattigerkkk** [comment]
[Wei Luo, Meng Cheng and Renyuan Zhang](https://github.com/tomcattigerkkk/Bittiger_CapstoneWork.git), only files for our model and testing result.
