### ISSUE TITLE
PyCharm运行时出错

### ISSUE THREAD

**Issue by iamxhc** [BitTiger-MP/DS502-AI-Engineer#7]
<img width="1397" alt="screen shot 2017-06-28 at 4 37 33 pm" src="https://user-images.githubusercontent.com/29770049/27675504-e811afca-5cdc-11e7-8a15-1e9bbe1bf28c.png">

老师好，我有以下两个问题：

1）第一次做作业的时候，使用PyCharm，但是在第一次Run的时候，就出现错误，已经截图。请老师看一下是什么地方出了问题。

2）有没有推荐的程序文本编译软件？

谢谢！

**Comment by ZezhouLi** [comment]
明天上课会演示的
